name: QuitSmokingDTx
options:
  bundleIdPrefix: com.dtx
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  QuitSmokingDTx:
    type: application
    platform: iOS
    sources:
      - path: QuitSmokingDTxApp
        excludes:
          - "**/*Tests.swift"
          - "**/*UITests.swift"
    resources:
      - path: QuitSmokingDTxApp/Resources
        excludes:
          - "**/.DS_Store"
    info:
      path: QuitSmokingDTxApp/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: QuitSmokingDTxApp/QuitSmokingDTx.entitlements
      properties:
        aps-environment: development
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dtx.quitsmoking
        PRODUCT_NAME: QuitSmokingDTx
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        Debug:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -Osize

  QuitSmokingDTxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - QuitSmokingDTxTests
    dependencies:
      - target: QuitSmokingDTx
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dtx.quitsmoking.tests
        GENERATE_INFOPLIST_FILE: YES

  QuitSmokingDTxUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - QuitSmokingDTxUITests
    dependencies:
      - target: QuitSmokingDTx
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dtx.quitsmoking.uitests
        TEST_TARGET_NAME: QuitSmokingDTx
        GENERATE_INFOPLIST_FILE: YES

schemes:
  QuitSmokingDTx:
    build:
      targets:
        QuitSmokingDTx: all
        QuitSmokingDTxTests: [test]
        QuitSmokingDTxUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - QuitSmokingDTxTests
        - QuitSmokingDTxUITests
    profile:
      config: Release
    archive:
      config: Release